// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjFrnqqOTSGpz8rw0LC0awpKQPmNO4bcI',
    appId: '1:227456918463:web:d381b3aea6732864cbb70a',
    messagingSenderId: '227456918463',
    projectId: 'gomakerfinalapp',
    authDomain: 'gomakerfinalapp.firebaseapp.com',
    storageBucket: 'gomakerfinalapp.appspot.com',
    measurementId: 'G-SMPC91G2K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWVNdgnPDQne5653Dq-i7awoZFr3QafWc',
    appId: '1:227456918463:android:89d1ee86d07028fccbb70a',
    messagingSenderId: '227456918463',
    projectId: 'gomakerfinalapp',
    storageBucket: 'gomakerfinalapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIL8qXAOgJ386GIv-3r3gAjVFrzYY3h5Q',
    appId: '1:227456918463:ios:75633f5608286e80cbb70a',
    messagingSenderId: '227456918463',
    projectId: 'gomakerfinalapp',
    storageBucket: 'gomakerfinalapp.appspot.com',
    iosBundleId: 'com.gomakersapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIL8qXAOgJ386GIv-3r3gAjVFrzYY3h5Q',
    appId: '1:227456918463:ios:6833c6ae8cf3fb6fcbb70a',
    messagingSenderId: '227456918463',
    projectId: 'gomakerfinalapp',
    storageBucket: 'gomakerfinalapp.appspot.com',
    iosBundleId: 'com.gomakersapp.RunnerTests',
  );
}
